import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from './constants';

const IDS = {
  ALERT_TITLE: `${REACT_COMPONENT_PREFIX}AlertTitle`
}

const ALERT_TITLE = {
  ID: IDS.ALERT_TITLE,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-alert-title`,
}

export {
  ALERT_TITLE
}
