import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from "./constants";

const IDS = {
  AUTOCOMPLETE: `${REACT_COMPONENT_PREFIX}Autocomplete`
}

const AUTOCOMPLETE = {
  ID: IDS.AUTOCOMPLETE,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-autocomplete`,
  GROUP_LABEL: `${IDS.AUTOCOMPLETE}-groupLabel`,
  GROUPED_GROUP_HOLDER: `${IDS.AUTOCOMPLETE}-groupUl`,
  DROP_DOWN_ITEM_TAG_NAME: `LI`,
  DROP_DOWN_ITEM_HTML_ELEMENT: `li`,
  ATTRIBUTE_COMPONENT: {
    GROUP_HEADERS: `groupHeaders`,
    OPTIONS: `options`
  },
  PRESENTATION_CLASS: `${IDS.AUTOCOMPLETE}-popper`
}

export {
  AUTOCOMPLETE
}
