import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from "./constants";

const IDS = {
  CARD_MEDIA: `${REACT_COMPONENT_PREFIX}CardMedia`
}

const CARD_MEDIA = {
  ID: IDS.CARD_MEDIA,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-card-media`,
}

export {
  CARD_MEDIA
}
