const REACT_COMPONENT_PREFIX = `Mui`;
const BASE_EMBER_COMPONENT_PREFIX = `ember-paper-react`;
const PAPER_REACT_HIDDEN_CLASS = `ember-paper-react-hide`;
const NOT_SET_COMPONENT_TYPE = `${BASE_EMBER_COMPONENT_PREFIX}-not-set`;
const GLOBAL_STRINGS = {
  CHILDREN_HOLDER_CLASS_NAME: `children-holder`
}

export {
  REACT_COMPONENT_PREFIX,
  BASE_EMBER_COMPONENT_PREFIX,
  PAPER_REACT_HIDDEN_CLASS,
  NOT_SET_COMPONENT_TYPE,
  GLOBAL_STRINGS
}
