import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from './constants';

const IDS = {
  DATE_PICKER: `${REACT_COMPONENT_PREFIX}DatePicker`
}

const DATE_PICKER = {
  ID: IDS.DATE_PICKER,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-date-picker`,
}

export {
  DATE_PICKER
}
