import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from './constants';

const IDS = {
  INPUT_LABEL: `${REACT_COMPONENT_PREFIX}InputLabel`
}

const INPUT_LABEL = {
  ID: IDS.INPUT_LABEL,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-input-label`,
}

export {
  INPUT_LABEL
}
