import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from "./constants";

const IDS = {
  RADIO: `${REACT_COMPONENT_PREFIX}Radio`
}

const RADIO = {
  ID: IDS.RADIO,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-radio`,
}

export {
  RADIO
}
