import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from "./constants";

const IDS = {
  SWITCH: `${REACT_COMPONENT_PREFIX}Switch`
}

const SWITCH = {
  ID: IDS.SWITCH,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-switch`,
}

export {
  SWITCH
}
