import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from './constants';

const IDS = {
  TAB_PANEL: `${REACT_COMPONENT_PREFIX}TabPanel`
}

const TAB_PANEL = {
  ID: IDS.TAB_PANEL,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-tab-panel`,
}

export {
  TAB_PANEL
}
