import { REACT_COMPONENT_PREFIX, BASE_EMBER_COMPONENT_PREFIX } from "./constants";

const IDS = {
  TEXT_FIELD: `${REACT_COMPONENT_PREFIX}TextField`
}

const TEXT_FIELD = {
  ID: IDS.TEXT_FIELD,
  COMPONENT_TYPE: `${BASE_EMBER_COMPONENT_PREFIX}-text-field`,
  INSERT_CLASS: `${REACT_COMPONENT_PREFIX}NativeSelect-select`,
  BASE_INPUT_CLASS: `${REACT_COMPONENT_PREFIX}InputBase-input`,
  ERROR_CLASS: `${REACT_COMPONENT_PREFIX}-error`,
  HELPER_CLASS: `${REACT_COMPONENT_PREFIX}FormHelperText-root`
}

export {
  TEXT_FIELD
}
